Update check_monerod_stuck

diff --git a/monero-cli/check_monerod_stuck b/monero-cli/check_monerod_stuck
--- a/monero-cli/check_monerod_stuck
+++ b/monero-cli/check_monerod_stuck
@@ -1,6 +1,8 @@
 #!/bin/bash
 
 height_file="/tmp/.monerod_height"
+today=`date +%Y%m%d%H%M%S`
+re='^[0-9]+$'
 
 # continue only when monerod service is running
 systemctl is-active --quiet monerod
@@ -11,13 +13,27 @@ if [ $? == 0 ] ; then
   old_height=`cat ${height_file} 2>/dev/null`
 
   # get new height
-  new_height=`timeout --foreground 5 monerod --config-file /etc/monerod.conf print_height | grep -P "^\d+$"`
-
-  re='^[0-9]+$'
+  # restart monerod if the cmd failed 6 times consecutively
+  new_height=`timeout --foreground 15 monerod --config-file /etc/monerod.conf print_height | grep -P "^\d+$"`
   if ! [[ $new_height =~ $re ]] ; then
-    # echo "monerod is NOT responding, restarting monerod service"
-    systemctl restart monerod
-    exit
+    new_height=`timeout --foreground 15 monerod --config-file /etc/monerod.conf print_height | grep -P "^\d+$"`
+    if ! [[ $new_height =~ $re ]] ; then
+      new_height=`timeout --foreground 15 monerod --config-file /etc/monerod.conf print_height | grep -P "^\d+$"`
+      if ! [[ $new_height =~ $re ]] ; then
+        new_height=`timeout --foreground 15 monerod --config-file /etc/monerod.conf print_height | grep -P "^\d+$"`
+        if ! [[ $new_height =~ $re ]] ; then
+          new_height=`timeout --foreground 15 monerod --config-file /etc/monerod.conf print_height | grep -P "^\d+$"`
+          if ! [[ $new_height =~ $re ]] ; then
+            new_height=`timeout --foreground 15 monerod --config-file /etc/monerod.conf print_height | grep -P "^\d+$"`
+            if ! [[ $new_height =~ $re ]] ; then
+              echo "CHECK_MONEROD_STUCK: restarted_$today"
+              systemctl restart monerod
+              exit
+            fi
+          fi
+        fi
+      fi
+    fi
   fi
 
   # save new height to file
@@ -27,8 +43,8 @@ if [ $? == 0 ] ; then
   # echo "new height: ${new_height}"
 
   # if new_height == old_height, restart monerod service 
-  if [ "$new_height" -eq "$old_height" ] ; then
-    # echo "restarting monerod service"
+  if [[ $old_height =~ $re ]] && [ "$new_height" -eq "$old_height" ] ; then
+    echo "CHECK_MONEROD_STUCK: restarted2_$today"
     systemctl restart monerod
   fi
 fi
